baseurl: "/GPTPardi"
url: "https://ouaisfieu.github.io"
remote_theme: just-the-docs/just-the-docs

title: "GPTPardi"
description: "Le dico qui pue du cul"
favicon_ico: "/favicon-96x96.png"



aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

aux_links:
  ouaisfi.eu: https://ouaisfi.eu

nav:
  - title: Notions
    url: /notions/



search_enabled: true
color_scheme: dark


collections:
  notions:
    output: true
  dossiers:               # â† Ajout de la collection
    output: true          # â† TrÃ¨s important pour gÃ©nÃ©rer les pages HTML
  belgique:                  # â† nom de la collection (tu peux mettre "myspot" si tu prÃ©fÃ¨res)
    output: true             # â† pour gÃ©nÃ©rer les pages HTML
    permalink: /belgique/:path/  # â† structure des URL
    sort_by: title           # â† optionnel, trie par titre

just_the_docs:
  collections:
    notions:
      name: MENU
      nav_fold: false
    dossiers:             # â† MÃªme structure pour dossiers
      name: Dossiers      # â† Nom affichÃ© dans la navigation
      nav_fold: false     # â† Mettre true si tu veux un repliement dans le menu
    belgique:
      name: ğŸ‡§ğŸ‡ª MY SPOT       # â† titre dans le menu de navigation
      nav_fold: true         # â† false = tout est affichÃ© dans le menu, true = repliÃ©



back_to_top: true
back_to_top_text: "â†‘ Haut de page"
